import type { Metadata } from 'next';
import Image from 'next/image';
import { Section, PageHero, Label, CTA } from '@/components/shared';
import { founders, principles, industries } from '@/lib/content';
export const metadata: Metadata = { title: 'About', description: 'Meet Scalidor, our five co-founders, and our mission to build intelligent software that scales into enduring businesses.', alternates: { canonical: '/about' } };
export default function About() { return <>
  <PageHero label="ABOUT SCALIDOR" title="Technology for" accent="what comes next." description="A U.S.-based technology company, founded by five co-founders with one ambition: build useful technology, solve meaningful problems, and turn strong ideas into scalable businesses." />
  <Section number="02"><div className="two-column"><div><Label>OUR STORY</Label><h2>More than<br />a software agency.</h2></div><div className="body-copy"><p>Scalidor was created around a simple belief: software should do more than complete a project. It should solve a real problem, create measurable value, and have the architecture and product thinking necessary to keep evolving.</p><p>That belief shaped us into a product-focused technology company. We develop SaaS platforms, AI systems, automation products, and industry software, alongside selected product-engineering services.</p><p>Our long-term goal is to build and operate multiple technology products while developing reusable knowledge, infrastructure, and engineering capabilities.</p></div></div></Section>
  <Section number="03" dark><div className="mission-grid"><div><Label>OUR MISSION</Label><h3>Build intelligent technology that solves real problems and scales into enduring businesses.</h3><p>We simplify complex operations through reliable, intuitive software. Every product should create useful value for the people and businesses it serves.</p></div><div><Label>OUR VISION</Label><h3>A global technology company. A portfolio of enduring products.</h3><p>We aim to create and operate category-defining software across SaaS, AI, automation, infrastructure, analytics, and industry technology.</p></div></div></Section>
  <Section number="04"><div className="section-heading"><div><Label>WHAT WE BELIEVE</Label><h2>Strong principles.<br />Practical decisions.</h2></div></div><div className="principle-list">{principles.map(([title, text], i) => <div className="principle-row" key={title}><span className="mono">0{i + 1}</span><h3>{title}</h3><p>{text}</p></div>)}</div></Section>
  <Section number="05"><div className="two-column"><div><Label>THE NAME</Label><h2 className="editorial-title">Built around<br />the idea of scale.</h2></div><div className="body-copy"><p><strong>Scal</strong> reflects scale, growth, and systems that expand as businesses grow. The second part represents structure, solidity, and a gateway connecting an idea with its next stage.</p><p>Together, Scalidor represents technology engineered for sustainable growth.</p><div className="name-statement"><span className="statement-logo-box"><Image src="/logo.png" alt="Scalidor Logo" width={48} height={48} className="statement-logo-img" /></span><div className="statement-text"><strong>Scalidor<span className="blue-period">.</span></strong><span className="mono">BUILT TO SCALE.</span></div></div></div></div></Section>
  <Section number="06"><div className="section-heading"><div><Label>FOUNDING TEAM</Label><h2>Five founders.<br />One company.</h2></div><p>A shared long-term vision of building meaningful technology businesses.</p></div><div className="founder-grid">{founders.map(name => <div className="founder-card" key={name}><div className="founder-initial" aria-hidden="true">{name.split(' ').filter(p => p !== 'MD').slice(0, 2).map(p => p[0]).join('')}</div><h3>{name}</h3><span className="mono">CO-FOUNDER</span></div>)}</div></Section>
  <Section number="07"><div className="section-heading"><div><Label>LONG-TERM DIRECTION</Label><h2>Designed to build<br />more than one product.</h2></div><p>Some products may use the Scalidor brand. Others may grow into independent brands, with the same engineering foundation.</p></div><div className="industry-tags">{industries.map((industry, i) => <a href="/products#future-industries" key={industry}><span className="mono">{String(i + 1).padStart(2, '0')}</span>{industry}</a>)}</div></Section><CTA number="08" />
</>; }
