import Link from 'next/link';
import type { Metadata } from 'next';
import { Bell, ChartNoAxesCombined, CreditCard, Database, KeyRound, MessageSquare, ShieldCheck, Sparkles } from 'lucide-react';
import { PageHero, Section, Label, CTA } from '@/components/shared';
import { ProductConcept } from '@/components/product-concept';
import { industries } from '@/lib/content';
export const metadata: Metadata = { title: 'Products', description: 'Explore Scalidor’s developing portfolio of industry software, real estate technology, and intelligent business systems.', alternates: { canonical: '/products' } };
export default function Products() { return <>
  <PageHero label="SCALIDOR PRODUCTS" title="Real industries." accent="Real possibilities." description="We are building a portfolio of scalable technology products for markets where better software can replace fragmented workflows, repetitive processes, and disconnected tools." />
  <Section number="02" id="real-estate"><div className="product-detail"><div><Label>INDUSTRY PLATFORM / 01</Label><div><span className="status mono">IN DEVELOPMENT</span></div><h2>Real Estate<br />Technology.</h2><p>Real-estate businesses manage properties, customers, websites, teams, and communication across too many disconnected tools.</p><p>We are developing integrated technology around the workflows behind modern real estate: from a new lead to ongoing property operations.</p><Link href="/contact?interest=product" className="button">Ask about this product</Link></div><ProductConcept /></div><ul className="capability-list">{['Property operations', 'Real-estate CRM', 'Project management', 'Property websites', 'Lead management', 'Team collaboration', 'Customer communication', 'Analytics & automation'].map(t => <li key={t}><span className="mono" style={{ color: 'var(--blue)' }}>+</span>{t}</li>)}</ul></Section>
  <Section number="03" id="intelligent-systems" dark><div className="product-detail"><div><Label>INTELLIGENT SYSTEMS / 02</Label><div><span className="status mono">RESEARCH & DEVELOPMENT</span></div><h2>Intelligent<br />Business Systems.</h2><p>Business workflows become more useful when information can lead directly to action. We are researching software that connects business processes with AI and automation.</p><p>Potential applications include document processing, intelligent search, AI assistants, customer-service automation, analytics, and operational recommendations.</p><Link href="/contact?interest=product" className="button button-light">Talk about an opportunity</Link></div><div className="ai-capability-map"><div className="map-core"><Sparkles size={28} /><span>INTELLIGENCE<br />WITH PURPOSE</span></div><div className="map-grid">{['Understand context', 'Process documents', 'Connect information', 'Automate workflows', 'Recommend actions', 'Keep people in control'].map(t => <div key={t}>{t}</div>)}</div></div></div></Section>
  <Section number="04" id="future-industries"><Label>LONG-TERM DIRECTION</Label><div className="section-heading"><h2>One foundation.<br />Many industries.</h2><p>We enter new markets when there is a strong problem, a meaningful opportunity, and a product that can create lasting value.</p></div><div className="industry-tags future-grid">{industries.map((t, i) => <Link href="/contact?interest=product" key={t}><span className="mono">{String(i + 1).padStart(2, '0')}</span>{t}</Link>)}</div></Section>
  <Section number="05" dark><Label>OUR PRODUCT PHILOSOPHY</Label><h2>A meaningful problem<br />comes first.</h2><div className="product-question-grid">{['Is the problem meaningful?', 'Do enough people experience it?', 'Can technology solve it better?', 'Will people pay for the solution?', 'Can it create recurring value?', 'Can it scale beyond a few customers?'].map((q, i) => <div key={q}><span className="mono">0{i + 1} /</span><h3>{q}</h3></div>)}</div></Section>
  <Section number="06"><div className="section-heading"><div><Label>SHARED TECHNOLOGY</Label><h2>Products should<br />strengthen each other.</h2></div><p>Reusable capabilities help future products grow more efficiently, while leaving room for each industry’s requirements.</p></div><div className="shared-system-grid">{[[KeyRound, 'Identity'], [CreditCard, 'Billing'], [Database, 'Data infrastructure'], [Bell, 'Notifications'], [ChartNoAxesCombined, 'Analytics'], [Sparkles, 'AI & automation'], [MessageSquare, 'Communications'], [ShieldCheck, 'Security']].map(([Icon, title]) => { const I = Icon as typeof KeyRound; return <div key={title as string} className="bracket"><I size={23} strokeWidth={1.5} /><span>{title as string}</span></div>; })}</div></Section><CTA number="07" />
</>; }
